services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_067
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - vendor_data:/var/www/html/vendor
      - node_modules_data:/var/www/html/node_modules
    ports:
      - "8000:8000"
    environment:
      APP_NAME: crud_uas_nim
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: db_uas_067
      DB_USERNAME: laraveluser
      DB_PASSWORD: laravelpass
      SESSION_DRIVER: database
      QUEUE_CONNECTION: database
      CACHE_STORE: database
      FILESYSTEM_DISK: public
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql_db_067
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_uas_067
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_067
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
  vendor_data:
  node_modules_data:
